name: deepligand
channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.1.10=py_0
  - backports=1.0=py36_1
  - backports.weakref=1.0rc1=py36_1
  - blas=1.1=openblas
  - bleach=1.5.0=py36_0
  - ca-certificates=2018.1.18=0
  - certifi=2018.1.18=py36_0
  - cffi=1.11.5=py36_0
  - freetype=2.8.1=0
  - h5py=2.7.1=py36_2
  - hdf5=1.10.1=2
  - html5lib=0.9999999=py36_0
  - jpeg=9b=2
  - libffi=3.2.1=3
  - libpng=1.6.34=0
  - libprotobuf=3.5.2=0
  - markdown=2.6.11=py_0
  - ncurses=5.9=10
  - numpy=1.14.2=py36_blas_openblas_200
  - olefile=0.45.1=py36_0
  - openblas=0.2.20=7
  - openssl=1.0.2n=0
  - pillow=5.0.0=py36_0
  - pip=9.0.1=py36_1
  - protobuf=3.5.2=py36_0
  - pycparser=2.18=py36_0
  - python=3.6.4=0
  - pyyaml=3.12=py36_1
  - readline=7.0=0
  - scikit-learn=0.19.1=py36_blas_openblas_201
  - scipy=1.0.1=py36_blas_openblas_200
  - setuptools=38.5.1=py36_0
  - six=1.11.0=py36_1
  - sqlite=3.20.1=2
  - tensorboard=1.5.1=py36_1
  - tensorflow=1.5.0=py36_0
  - tk=8.6.7=0
  - webencodings=0.5=py36_0
  - werkzeug=0.14.1=py_0
  - wheel=0.30.0=py36_2
  - xz=5.2.3=0
  - yaml=0.1.7=0
  - zlib=1.2.11=0
  - intel-openmp=2018.0.0=hc7b2577_8
  - keras=2.1.4=py36_0
  - libgcc-ng=7.2.0=h7cc24e2_2
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.2.0=h9f7466a_2
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - mkl=2018.0.1=h19d6760_4
  - cuda90=1.0=h6433d27_0
  - pytorch=0.3.1=py36_cuda9.0.176_cudnn7.0.5_2
  - torchvision=0.2.0=py36h17b6947_1
  - pip:
    - alabaster==0.7.12
    - allennlp==0.8.0
    - asn1crypto==0.24.0
    - astroid==2.1.0
    - attrs==17.4.0
    - aws-xray-sdk==0.95
    - awscli==1.16.81
    - babel==2.6.0
    - backcall==0.1.0
    - bilm==0.1.post5
    - blitzdb==0.4.4
    - boto==2.49.0
    - boto3==1.9.71
    - botocore==1.12.71
    - chardet==3.0.4
    - click==6.7
    - colorama==0.3.9
    - conllu==0.11
    - cookies==2.2.1
    - cryptography==2.4.2
    - cycler==0.10.0
    - cymem==1.31.2
    - cytoolz==0.8.2
    - decorator==4.2.1
    - dill==0.2.7.1
    - docker==3.6.0
    - docker-pycreds==0.4.0
    - docutils==0.14
    - ecdsa==0.13
    - editdistance==0.5.2
    - flaky==3.4.0
    - flask==1.0.2
    - flask-cors==3.0.7
    - ftfy==5.5.0
    - funcsigs==1.0.2
    - future==0.16.0
    - gevent==1.3.6
    - greenlet==0.4.15
    - hyperopt==0.1
    - idna==2.6
    - imagesize==1.1.0
    - ipykernel==5.1.0
    - ipython==7.1.1
    - ipython-genutils==0.2.0
    - isort==4.3.4
    - itsdangerous==1.1.0
    - jedi==0.13.1
    - jinja2==2.10
    - jmespath==0.9.3
    - jsondiff==1.1.1
    - jsonnet==0.10.0
    - jsonpickle==1.0
    - jsonschema==2.6.0
    - jupyter-client==5.2.3
    - jupyter-core==4.4.0
    - kiwisolver==1.0.1
    - lazy-object-proxy==1.3.1
    - markupsafe==1.1.0
    - matplotlib==2.2.3
    - mccabe==0.6.1
    - mock==2.0.0
    - moto==1.3.4
    - msgpack==0.5.6
    - msgpack-numpy==0.4.1
    - msgpack-python==0.5.6
    - murmurhash==0.28.0
    - nbformat==4.4.0
    - networkx==2.1
    - nltk==3.2.5
    - nose==1.3.7
    - numpydoc==0.8.0
    - overrides==1.9
    - packaging==18.0
    - pandas==0.23.4
    - parsimonious==0.8.0
    - parso==0.3.1
    - pathlib==1.0.1
    - pbr==5.1.1
    - pep8==1.7.1
    - pexpect==4.6.0
    - pickleshare==0.7.5
    - plac==0.9.6
    - pluggy==0.6.0
    - preshed==1.0.0
    - prompt-toolkit==2.0.7
    - psutil==5.4.3
    - ptyprocess==0.6.0
    - py==1.5.2
    - pyaml==18.11.0
    - pyasn1==0.4.4
    - pycryptodome==3.7.2
    - pyflakes==2.0.0
    - pygments==2.2.0
    - pylint==2.2.2
    - pymongo==3.6.1
    - pyparsing==2.3.0
    - pytest==3.4.2
    - python-dateutil==2.7.5
    - python-jose==2.0.2
    - pytorch-pretrained-bert==0.3.0
    - pytz==2017.3
    - pyzmq==17.1.2
    - ray==0.3.1
    - redis==2.10.6
    - regex==2017.4.5
    - requests==2.18.4
    - responses==0.10.5
    - rpy2==2.9.4
    - rsa==3.4.2
    - s3transfer==0.1.13
    - seaborn==0.9.0
    - snowballstemmer==1.2.1
    - spacy==2.0.11
    - sphinx==1.8.3
    - sphinxcontrib-websupport==1.1.0
    - sqlalchemy==1.2.16
    - sqlparse==0.2.4
    - tensorboardx==1.2
    - tensorflow-gpu==1.2.0
    - tensorflow-tensorboard==1.5.1
    - termcolor==1.1.0
    - thinc==6.10.2
    - toolz==0.9.0
    - torch==1.0.0
    - torchsummary==1.5.1
    - torchtext==0.2.1
    - tornado==5.1.1
    - tqdm==4.20.0
    - traitlets==4.3.2
    - typed-ast==1.1.1
    - ujson==1.35
    - unidecode==1.0.23
    - urllib3==1.22
    - wcwidth==0.1.7
    - websocket-client==0.54.0
    - wrapt==1.10.11
    - xmltodict==0.11.0

